# Generated by Django 4.2.11 on 2024-03-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofiles',
            fields=[
                ('s_no', models.AutoField(db_column='S.No', primary_key=True, serialize=False)),
                ('profileid', models.CharField(db_column='ProfileID', max_length=7)),
                ('profilename', models.CharField(db_column='ProfileName', max_length=50)),
                ('masterflag', models.CharField(db_column='MasterFlag', max_length=2)),
                ('dateofbirth', models.DateTimeField(db_column='DateOfBirth')),
                ('birthlatitude', models.FloatField(db_column='BirthLatitude')),
                ('birthlongitude', models.FloatField(db_column='BirthLongitude')),
                ('birthoffset', models.FloatField(db_column='BirthOffset')),
                ('otherdetail1', models.CharField(db_column='OtherDetail1', max_length=50)),
                ('otherdetail2', models.CharField(db_column='OtherDetail2', max_length=50)),
            ],
            options={
                'db_table': 'userprofiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('s_no', models.AutoField(db_column='S.No', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='UserName', max_length=50)),
                ('usertoken', models.CharField(db_column='UserToken', max_length=7)),
                ('email', models.CharField(db_column='Email', max_length=50)),
                ('password', models.CharField(db_column='Password', max_length=50)),
                ('dateofbirth', models.DateTimeField(db_column='DateOfBirth')),
                ('birthlocation', models.CharField(db_column='BirthLocation', max_length=50)),
                ('birthlatitude', models.CharField(db_column='BirthLatitude', max_length=50)),
                ('birthlongitude', models.CharField(db_column='BirthLongitude', max_length=50)),
                ('birthoffset', models.IntegerField(db_column='BirthOffset')),
                ('primarylocation', models.CharField(db_column='PrimaryLocation', max_length=50)),
                ('primarylatitude', models.FloatField(db_column='PrimaryLatitude')),
                ('primarylongitude', models.FloatField(db_column='PrimaryLongitude')),
                ('primaryoffset', models.IntegerField(db_column='PrimaryOffset')),
                ('usertype', models.CharField(db_column='UserType', max_length=5)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
