# Generated by Django 4.2.11 on 2024-03-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languagetable',
            fields=[
                ('s_no', models.AutoField(db_column='S.No', primary_key=True, serialize=False)),
                ('messageid', models.IntegerField(db_column='MessageID')),
                ('messageen', models.TextField(db_column='MessageEN')),
                ('messagehi', models.TextField(db_column='MessageHI')),
                ('messagege', models.TextField(db_column='MessageGE')),
            ],
            options={
                'db_table': 'languagetable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersSnsTable',
            fields=[
                ('s_no', models.AutoField(db_column='S.No', primary_key=True, serialize=False)),
                ('usertoken', models.CharField(db_column='UserToken', max_length=7)),
                ('emailid', models.CharField(blank=True, db_column='EmailID', max_length=20, null=True)),
                ('firebasetoken', models.TextField(db_column='FirebaseToken')),
                ('amazonarn', models.TextField(db_column='AmazonARN')),
            ],
            options={
                'db_table': 'users_sns_table',
                'managed': False,
            },
        ),
    ]
